# Generated by Django 5.1.5 on 2025-01-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_created_at_order_date_ordered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vegetable',
            old_name='price_per_kg',
            new_name='price',
        ),
        migrations.AddField(
            model_name='vegetable',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
